services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./webapp/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:  <-- REMOVED FOR SECURITY (Database not exposed to internet)
    #   - "5432:5432"
    networks:
      - kairoscope-net

  ai:
    build: ./ai
    restart: always # Keep it running
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - DB_HOST=database
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=5432
    depends_on:
      - database
    volumes:
      - ./ai:/app
    networks:
      - kairoscope-net

  api:
    build: ./webapp/api
    ports:
      - "8081:80"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=15&charset=utf8"
      APP_ENV: prod
      APP_DEBUG: 0
      CORS_ALLOW_ORIGIN: '^https?://(localhost|kairoscope\.maxboudier\.fr)$'
      SYMFONY_TRUSTED_HOSTS: '^(localhost|kairoscope\.maxboudier\.fr)$'
    volumes:
      - ./webapp/api:/var/www/html
      - vendor_data:/var/www/html/vendor
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - kairoscope-net
    command: sh -c "composer install --no-dev --optimize-autoloader && apache2-foreground"

  front:
    build: ./webapp/front
    ports:
      - "80:80" # Nginx runs on 80 inside container
    # No volumes needed for code in prod (baked into image)
    # volumes:
    #   - ./webapp/front:/app
    #   - /app/node_modules
    depends_on:
      - api
    networks:
      - kairoscope-net
    # No command needed (uses Dockerfile CMD)

networks:
  kairoscope-net:
    driver: bridge

volumes:
  db_data:
  vendor_data:
