name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Créer le dossier s'il n'existe pas
            mkdir -p /home/${{ secrets.USERNAME }}/projet/Kairoscope
            cd /home/${{ secrets.USERNAME }}/projet/Kairoscope
            
            # Initialiser git si ce n'est pas fait (premier déploiement)
            if [ ! -d ".git" ]; then
              git clone https://github.com/MaxBoudier/Kairoscope.git .
            fi

            # Récupérer la dernière version
            git fetch origin
            git reset --hard origin/main

            # Écrire le fichier .env à partir du Secret GitHub au root pour Docker Compose
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            
            # Copier le .env dans le dossier api pour qu'il soit monté dans le volume du conteneur
            cp .env webapp/api/.env

            # Lancer Docker Compose (Build force la reconstruction pour prendre en compte les nouveaux args)
            # --remove-orphans nettoie les conteneurs obsolètes
            docker compose up -d --build --remove-orphans

            # Nettoyage des images inutilisées pour économiser de l'espace disque
            docker image prune -f
